#!/usr/bin/env python3
"""
test_plugin - Lyrixa Plugin
A test plugin

Auto-generated by Lyrixa Plugin System
"""

def execute(command, **kwargs):
    """
    Main plugin execution function

    Args:
        command (str): The command to execute
        **kwargs: Additional arguments

    Returns:
        dict: Result of the command execution
    """

    if command == "hello":
        return {
            "message": "Hello from test_plugin!",
            "plugin": "test_plugin",
            "status": "active"
        }

    elif command == "info":
        return {
            "name": "test_plugin",
            "description": "A test plugin",
            "capabilities": ["hello", "info"],
            "version": "1.0.0"
        }

    else:
        return {
            "error": f"Unknown command: {command}",
            "available_commands": ["hello", "info"]
        }


def initialize():
    """Called when plugin is activated"""
    print(f"🔌 test_plugin plugin initialized")
    return True


def cleanup():
    """Called when plugin is deactivated"""
    print(f"🔌 test_plugin plugin cleaned up")
    return True


# Plugin metadata (optional)
PLUGIN_INFO = {
    "name": "test_plugin",
    "friendly_name": "Test Plugin",
    "category": "utility",
    "tags": ["custom", "utility", "lyrixa"]
}
