#!/usr/bin/env python3
"""
hello_world_1 - Lyrixa Plugin
A simple hello world plugin

Auto-generated by Lyrixa Plugin System
"""

def execute(command, **kwargs):
    """
    Main plugin execution function
    
    Args:
        command (str): The command to execute
        **kwargs: Additional arguments
    
    Returns:
        dict: Result of the command execution
    """
    
    if command == "hello":
        return {
            "message": "Hello from hello_world_1!",
            "plugin": "hello_world_1",
            "status": "active"
        }
    
    elif command == "info":
        return {
            "name": "hello_world_1",
            "description": "A simple hello world plugin",
            "capabilities": ["hello", "info"],
            "version": "1.0.0"
        }
    
    else:
        return {
            "error": f"Unknown command: {command}",
            "available_commands": ["hello", "info"]
        }


def initialize():
    """Called when plugin is activated"""
    print(f"🔌 hello_world_1 plugin initialized")
    return True


def cleanup():
    """Called when plugin is deactivated"""
    print(f"🔌 hello_world_1 plugin cleaned up")
    return True


# Plugin metadata (optional)
PLUGIN_INFO = {
    "name": "hello_world_1",
    "friendly_name": "Hello World 1",
    "category": "utility",
    "tags": ["custom", "utility", "lyrixa"]
}
